name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'     # ← Pin a real version, not "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web --release

      - name: Build macOS
        run: flutter build macos --release
